name: Audit

on: [push]
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]

jobs:
  test:
    runs-on: golang:1.21.8
    steps:
      - uses: actions/checkout@v2

      - name: Verify dependencies
        run: go mod verify

  build:
    runs-on: golang:1.21.8
    steps:
      - uses: action/checkout@v2

      - name: build binary
        run: go mod binary

#  build-linux:
#    runs-on: golang:1.21.8
#    env:
#      GOARCH: amd64
#      GODS: linux
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Verify dependencies
#        run: go mod verify
#
#      - name: Build
#        run: go build -o ./remote-control-linux
#
#  build-windows:
#    runs-on: golang:1.21.8
#    env:
#      GOARCH: amd64
#      GODS: windows
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Verify dependencies
#        run: go mod verify
#
#      - name: Build
#        run: go build -o ./remote-control-win
#
#  build-ra:
#    runs-on: golang:1.21.8
#    env:
#      GOARCH: amd64
#      GODS: linux
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Verify dependencies
#        run: go mod verify
#
#      - name: Build
#        run: go build -o ./remote-control-win
