name: Audit

on: [push]
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]


jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Installing GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Verify dependencies
        run: go mod verify

      - name: Build linux version
        run: |
          export GOARCH: amd64
          export GODS: linux 
          go build -o ${{ github.repository }}-linux
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository }}-linux
          path: ${{ github.repository }}-linux
